name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  file_picker: ^8.0.6
  share_plus: ^10.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        # - asset: assets/fonts/Vazirmatn-Bold.ttf # Removed as file not found
        #   weight: 700
